<h1>Neue Aktie hinzufügen</h1>

<p>Hier können Sie eine neue Aktie hinzufügen. Dazu benötigen Sie das Symbol der Aktie. Hier sind ein paar Beispiele:</p>
<ul>
	<li>SAP.DE</li>
	<li>RWE.DE</li>
	<li>LHA.DE</li>
	<li>BMW.DE</li>
	<li>DTE.DE</li>
</ul>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('stock', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('symbol'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();