<h1>Aktie löschen</h1>

<p>Sind Sie sicher, dass Sie die Aktie mit dem Symbol '<?php echo $this->escapeHtml($stock->symbol); ?>' löschen möchten?</p>

<?php
$url = $this->url('stock', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $stock->id; ?>" />
    <input type="submit" name="del" value="Ja" />
    <input type="submit" name="del" value="Nein" />
</div>
</form>