<h1>Chart für: <?php echo $stock->getSymbol(); ?></h1>

<p>
	Hier wird der Chart für <?php echo $stock->getSymbol(); ?> dargestellt.<br/>
	Verwendet wird hier die JS-Bibliothek EaselJS.<br/>
	3 Verschiedene Zeiträume und 3 Varianten des Simple Moving Average (SMA) können angezeigt werden.
</p>

<canvas id="chartCanvas">
	Sollte der Chart bei Ihnen nicht erscheinen, so wird dies von Ihrem Browser nicht unterstützt.
	Bitte benutzen Sie einen aktuelleren Browser.
</canvas>

<div id="chartNavigation">

	<div id="chooseChartPeriod">
		Zeitraum:
		<nav id="monthSelector">
			<a href="#" class="activated">1 Monat</a> |
			<a href="#">2 Monate</a> |
			<a href="#">3 Monate</a>
		</nav>
	</div>

	<div id="chooseChartIndicators">
		Indikatoren:
		<nav id="smaSelector">
			<a href="#">SMA(10)</a> |
			<a href="#">SMA(20)</a> |
			<a href="#">SMA(30)</a>
		</nav>
	</div>
</div>

<script>
	// set size of canvas element
	var windowHeight = $(window).height();
	$("#chartCanvas").attr('width', $("#contentContainer").width());
	$("#chartCanvas").attr('height', windowHeight - 240);
	$("#chartCanvas").css('height', windowHeight - 240);

	$("#monthSelector a").click(function() {

		$(this).parent().children().removeClass('activated');
		$(this).addClass('activated');

		var days = null;
		switch ($(this).html()) {
			case '1 Monat': days = 20; break;
			case '2 Monate': days = 40; break;
			case '3 Monate': days = 60; break;
		}
		loadPrices(days);
	});

	$("#smaSelector a").click(function() {

		var sma = null;
		switch ($(this).html()) {
			case 'SMA(10)': sma = 10; break;
			case 'SMA(20)': sma = 20; break;
			case 'SMA(30)': sma = 30; break;
		}

		if ($(this).hasClass('activated')) {
			$(this).removeClass('activated');
			stage.removeChild(movingAverageContainers[sma]);
			delete movingAverageContainers[sma];
		}
		else {
			$(this).addClass('activated');
			var movingAverageData = calculateMovingAverage(sma);
			movingAverageContainers[sma] = drawMovingAverage(sma, movingAverageData);
			stage.addChild(movingAverageContainers[sma]);
		}
		stage.update();
	});
</script>

<script src="/js/EaselJS-release_v0.6.1/lib/easeljs-0.6.1.min.js"></script>
<script src="/js/charts/CandleStickContainer.js"></script>
<script src="/js/charts/init.js"></script>

<script>
	var stock = new Object();
	stock.id = '<?php echo $stock->getId(); ?>';
	stock.symbol = '<?php echo $stock->getSymbol(); ?>';
	init();
</script>