<h1>Aktienkurse</h1>

<h2>Zend Framework 2 + mongodb + html5 canvas</h2>

<p>
	Mit diesem Projekt möchte ich demonstrieren, wie man mit dem Zend Framework 2 in
	Verbindung mit mongodb und dem neuen HTML 5 Canvas Element interaktive Charts
	darstellen kann.
</p>
<ul>
	<li><a href="/">Startseite</a></li>
	<li><a href="/stock">Aktien (mongodb)</a></li>
	<li><a href="/album">Alben (mysql)</a></li>
	<li><a href="/stock/github">Github</a></li>
</ul>

<br/>

<img src="/img/aktien.jpg" />

<br/>
<br/>