<h1>the "stocks" collection (mongo db)</h1>

<p>
    <!--<a href="<?php echo $this->url('stock', array('action'=>'add'));?>">Add a new stock</a>-->
	<a href="/stock/add">Add a new stock</a>
</p>

<table class="table">
<tr>
    <th>Symbol</th>
    <th>Action</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($stocks as $stock) : ?>

<tr>
    <td><?php echo $this->escapeHtml($stock->symbol);?></td>
    <td>
		<a href="<?php echo $this->url('stock', array('action'=>'edit', 'id' => $stock->id));?>">Edit</a> |
		<a href="http://de.finance.yahoo.com/q?s=<?php echo $stock->getSymbol(); ?>" target="_blank">View yahoo details</a> |
		<a href="<?php echo $this->url('stock', array('action'=>'getHistoricalPricesOfStock', 'id' => $stock->id));?>">Get historical prices from yahoo</a> |
        <a href="<?php echo $this->url('stock', array('action'=>'delete', 'id' => $stock->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
