<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
		<meta name="robots" content="noindex">
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
							->prependStylesheet($this->basePath() . '/css/style.css')
							->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
							->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
		<div id="topNavigation">
			<a href="/">Home</a> |
			<a href="/stock">Stocks (mongodb)</a> |
			<a href="/album">Album tutorial (mysql)</a> |
			<a href="/stock/github">Github</a>
		</div>
        <div id="contentContainer">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
