<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class StockDocumentPriceHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['stock'])) {
            $reference = $data['stock'];
            if (isset($this->class->fieldMappings['stock']['simple']) && $this->class->fieldMappings['stock']['simple']) {
                $className = $this->class->fieldMappings['stock']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['stock'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['stock']->setValue($document, $return);
            $hydratedData['stock'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['date'])) {
            $value = $data['date'];
            $return = (string) $value;
            $this->class->reflFields['date']->setValue($document, $return);
            $hydratedData['date'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['open'])) {
            $value = $data['open'];
            $return = (float) $value;
            $this->class->reflFields['open']->setValue($document, $return);
            $hydratedData['open'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['high'])) {
            $value = $data['high'];
            $return = (float) $value;
            $this->class->reflFields['high']->setValue($document, $return);
            $hydratedData['high'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['low'])) {
            $value = $data['low'];
            $return = (float) $value;
            $this->class->reflFields['low']->setValue($document, $return);
            $hydratedData['low'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['close'])) {
            $value = $data['close'];
            $return = (float) $value;
            $this->class->reflFields['close']->setValue($document, $return);
            $hydratedData['close'] = $return;
        }
        return $hydratedData;
    }
}